c_compiler:
  - gcc                      # [linux]
  - clang                    # [osx]
  - vs2019                   # [win]
c_compiler_version:            # [unix]
  - 15                         # [osx]
  - 10                         # [linux]
cxx_compiler:
  - gxx                      # [linux]
  - clangxx                  # [osx]
  - vs2019                   # [win]
cxx_compiler_version:          # [unix]
  - 15                         # [osx]
  - 10                         # [linux]
llvm_openmp:                   # [osx]
  - 15                         # [osx]

# Experimenting with how to include a build variant
occt:
  - '*=*novtk*'
